module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  aggregator: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contact_block: 0
  contact_storage: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  facebook_comments: 0
  fb_likebox: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  feeds_xpathparser: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  jsonapi: 0
  kint: 0
  link: 0
  media: 0
  menu_ui: 0
  node: 0
  options: 0
  owlcarousel: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  random_number_field: 0
  random_sort: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  zurb_foundation: 0
  bootstrap: 0
  rendroid: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
