features:
  comment_user_picture: 1
  comment_user_verification: null
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://header/favicon.png'
  url: ''
  use_default: 0
favicon:
  mimetype: image/png
  path: 'public://header/favicon.png'
  url: 'http://deped-dauin.dd:81/themes/contrib/bootstrap/favicon.ico'
  use_default: 0
zurb_foundation_status_in_reveal: 0
zurb_foundation_use_respondjs: 1
zurb_foundation_meta_header_grid: 1
zurb_foundation_top_bar_enable: '0'
zurb_foundation_top_bar_grid: 0
zurb_foundation_top_bar_sticky: 0
zurb_foundation_top_bar_is_hover: 0
zurb_foundation_top_bar_menu_text: ''
zurb_foundation_top_bar_custom_back_text: 0
zurb_foundation_top_bar_back_text: ''
zurb_foundation_top_bar_search: 0
zurb_foundation_page_site_name: 0
zurb_foundation_page_site_logo: 0
zurb_foundation_page_account_info: 0
zurb_foundation_disable_base_css: 1
zurb_foundation_disable_base_js: 1
schemas:
  bootstrap: 8000
  rendroid: 8000
table_responsive: '-1'
region_wells:
  meta_header: ''
  header: ''
  help: ''
  highlighted: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
  left_off_canvas: ''
  right_off_canvas: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
