<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormState;
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Ajax\AfterCommand;
use Drupal\Core\Ajax\AddCssCommand;
use Drupal\Core\Ajax\InsertCommand;
use Drupal\image\Plugin\Field\FieldType\ImageItem;

use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Symfony\Component\HttpFoundation\Request;

use Drupal\contact\MailHandler;
use Drupal\Core\Url;

use Drupal\Core\User;
use Drupal\votingapi\Entity\Vote;

function random_sort_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  // ksm($form_id);

    if($form_id == 'contact_message_inquire_form'){

        // ksm($form_state::hasAnyErrors());
        // ksm($form_state->getErrors());
        // $form_state->setErrorByName("WARNING","PLEASE LOGIN");
        // $form_state->setExecuted();
        // ksm($form);
        // ksm("test");
        // Vote->setValue(12);
    }

    if($form_id == 'user_login_form'){
      $email = "testsss1234@gmail.com";
        // $name = substr($mail, 0, strpos($mail, '@'));

       // Make sure the user name isn't already taken.
        $query = db_select('users', 'u')
          ->fields('u', array('uid'))->execute();
          // ->condition('u.name', $name)
        // ksm($query->fetchAll());
        $results = $query->fetchAll();
        foreach ($results as $key => $value) {
          if($value->uid != '0') {
            $user = Drupal\user\Entity\User::load($value->uid);
            // ksm($user);
            // ksm($user->getEmail());

            if($user->getEmail() !== $email ){
                // $account = new stdClass();
                // $account->name = "ren";
                // $account->mail = $email;
                // $account->init = $email;
                // $account->status = 1;
                // $account->timezone = "Asia/Manila";
                // $account->roles = "authenticated";

                $account = [];
                // $account
                // $account['uid'] =
                $account['preferred_langcode'] = "en";
                $account['name'] = "test11";
                $account['pass'] = "1234";
                $account['mail'] = $email;
                $account['init'] = $email;
                $account['status'] = 1;
                $account['timezone'] = "Asia/Manila";
                $account["roles"] = "authenticated";
                // ksm($account);


                // ksm($account);
                // Drupal\user\Entity\User::create($account)->save();
                // $new_user->save();
                // ksm($new_user);
                // ksm($account);
                // user_save($account);

            }
          }
        }


        // user_save($account);
        // ksm($name);
        // If the user name is taken, append a random string to the end of it.
        if ($result->uid) { $name .= '-' . user_password(); }

        // Build the user account object and then save it.
        // $account = new stdClass();
        // $account->name = $name;
        // $account->mail = $mail;
        // $account->init = $mail;
        // $account->pass = user_password();
        // $account->status = 1;
        // user_save($account);
        // if ($account->uid) {
        //   drupal_set_message('Created new user with id %uid', array('%uid' => $account->uid));
        // }
        // ksm($account);
         // $form_state->setRedirect("<front>");
         // ksm($form_state);
    }
}




function random_sort_preprocess_page(&$variables) {
  // $variables['page']['#cache']['contexts'][] = 'route';
  // $urlRoute = \Drupal::routeMatch()->getRouteName();
  // ksm(\Drupal::routeMatch());
  // if ($urlRoute == 'view.drumstick_page.page_1' ) {
  //   ksm($variables);
  //   unset($variables['#cache']['contexts']);
  //   $variables['#attached']['library'][] = 'random_sort/custom-styling';
  //   ksm($variables);
  // }
}
