<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormState;
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Ajax\AfterCommand;
use Drupal\Core\Ajax\AddCssCommand;
use Drupal\Core\Ajax\InsertCommand;
use Drupal\image\Plugin\Field\FieldType\ImageItem;

use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Symfony\Component\HttpFoundation\Request;

use Drupal\contact\MailHandler;
use Drupal\Core\Url;
function random_sort_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  // ksm($form_id);

    if($form_id == 'contact_message_inquire_form'){

        // ksm($form_state::hasAnyErrors());
        // ksm($form_state->getErrors());
        // $form_state->setErrorByName("WARNING","PLEASE LOGIN");
        // $form_state->setExecuted();
        // ksm($form);
    }

    if($form_id == 'user_login_form'){
       
         // $form_state->setRedirect("<front>");
         // ksm($form_state);
    }
}




function random_sort_preprocess_page(&$variables) {
  // $variables['page']['#cache']['contexts'][] = 'route';
  // $urlRoute = \Drupal::routeMatch()->getRouteName();
  // ksm(\Drupal::routeMatch());
  // if ($urlRoute == 'view.drumstick_page.page_1' ) {
  //   ksm($variables);
  //   unset($variables['#cache']['contexts']);
  //   $variables['#attached']['library'][] = 'random_sort/custom-styling';
  //   ksm($variables);
  // }
}




