<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormState;
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Ajax\AfterCommand;
use Drupal\Core\Ajax\AddCssCommand;
use Drupal\Core\Ajax\InsertCommand;
use Drupal\image\Plugin\Field\FieldType\ImageItem;
// use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Symfony\Component\HttpFoundation\Request;
function random_sort_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  ksm($form_id);

    if($form_id == 'node_airtist_form'){
       // ksm($form_state);
       // $ajax = \Drupal::service('ajax_response.attachments_processor');
       $response = new AjaxResponse();  
       // $response->addCommand(new AlertCommand('renierjohn hahahahahah'));
       // // $Selector = '.myclass';
       // $content = '<p>my htlm content</p>';
       // $settings = ['my-setting' => 'setting',]; 
       // $response->addCommand(new AfterCommand($Selector, $content, $settings));
       // $response->addCommand(new AddCssCommand('<style>label{color:red;}</style>'));
       // $response->addCommand(new InsertCommand($parking));
       // $response->addCommand(new AlertCommand('renierjohn hahahahahah'));
       // return $response;
        // $form['field_car_company']['widget'][0]['value'] = array(
        //     '#title' => 'Client company',
        //     '#type' => 'textfield',
        //     '#required' => TRUE,
        //     '#ajax' => array(
        //           'callback' => 'ajax_callback_custom',
        //           'event' => 'keyup',
        //           'wrapper'=>'field_artist_name',
        //           'progress' => array(
        //             'type' => 'throbber',
        //             'message' => 'renier john',
        //             ),
        //     )
        // );

        // $form['field_artist_name']['widget'][0]['value']['#default_value'] ='qwqwqwqwq';
        // ksm($form['field_artist_main_image']['widget'][0]['#value_callback']);
        // ksm($form_state);
    }
}




function random_sort_preprocess_page(&$variables) {
  // $variables['page']['#cache']['contexts'][] = 'route';
  // $urlRoute = \Drupal::routeMatch()->getRouteName();
  // ksm(\Drupal::routeMatch());
  // if ($urlRoute == 'view.drumstick_page.page_1' ) {
  //   ksm($variables);
  //   unset($variables['#cache']['contexts']);
  //   $variables['#attached']['library'][] = 'random_sort/custom-styling';
  //   ksm($variables);
  // }
}


